cebra/models/model.py
tests/test_models.py

Some newer models require pytorch >= 1.12. To avoid making this a hard dependency, this PR adds functionality to check the pytorch version, and only registers compatible models.

Raise error on old pytorch version

---

.github/workflows/build.yml
CITATION.cff
Makefile
PKGBUILD
cebra/__init__.py
docs/root/index.html
docs/source/conf.py
docs/source/installation.rst
reinstall.sh
setup.cfg

- Several updates of references to the now [released paper](https://www.nature.com/articles/s41586-023-06031-6) in README, docs, and CITATION.cff
- Bump version to 0.2.0rc4

Release 0.2.0rc4

---

cebra/data/helper.py
tests/test_data_helper.py

Multiple tests failed internally and on this repo (e.g., in #20 , #25, #26) due to a numerical issue in `OrthogonalProcrustesAlignment` when a too small value for `subsample` is used.
This PR fixes this by setting the default to `None`, which means that all points available in the embedding are used for alignment. This is the numerically best option. In other cases, warnings are emitted, when e.g. the values of `subsample` is smaller than the number of points in the dataset, or when the number of `subsample` is smaller than 1000 (a reasonable default).
This PR also improves the tests, and removes the `atol` value of several tests, or at least decreases it slightly to avoid false negatives in the future.
---
Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/647
Fix …

Remove `subsample` default in `OrthogonalProcrustesAlignment`, improve tests

---

.github/workflows/doc-coverage.yml
.github/workflows/docs.yml

- The documentation status workflow needs to be updated to the `pull_request_target` as it uses the `GITHUB_TOKEN` to run.
- For the docs workflow, since all repos are public, we removed the token in the checkout action which allows external contributors to run this workflow.
Close #32

Fix action workflow definitions for external contributors

---

setup.cfg

It seems like `scikit-learn` updated to 1.3.0 a few hours ago (https://pypi.org/project/scikit-learn/#history), but their index for doc build is not updated. This causes and issue that we tracked in https://github.com/AdaptiveMotorControlLab/CEBRA-dev/issues/649.
I propose to temporarily pin sklearn below 1.3.0 *only for docs build*, which wont affect the main package, to fix this issue. Then, once the object files are updated and published by sklearn, we can unpin again. I will set a reminder to do that within a few weeks.
This will otherwise block merging a few PRs in the upcoming days.
---
Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/issues/649

For docs build, limit scikit-learn version

---

.github/workflows/doc-coverage.yml

To fix some issues we saw e.g. in #30 when running the doc coverage action (https://github.com/AdaptiveMotorControlLab/CEBRA/actions/runs/5415972675/jobs/9845039355?pr=30). I temporarily commented out the part of the workflow that posts the comment to the PR, the check itself is still run.

Temporarily disable PR comment to report doc coverage

---

cebra/data/assets.py
cebra/data/base.py
cebra/datasets/assets.py
cebra/datasets/hippocampus.py
tests/test_datasets.py

This pull request allows automatic download of datasets e.g. `cebra.datasets.init('rat-hippocampus-single')`. We will support the rat dataset, the ALLEN dataset (neuropixel and calcium) and the monkey reaching dataset.
Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/641

Automatically download the rat-hippocampus dataset

---

docs/source/conf.py

Before, lines with `...` were not copied by using the copy button. This PR fixes that behavior by adapting the config for the sphinx copybutton package.
copied code:
``` python
import cebra.distributions.multisession as cebra_distributions_multisession
import cebra.integrations.sklearn.dataset as cebra_sklearn_dataset
import cebra.data
import torch
from torch import nn
session1 = torch.rand(100, 30)
session2 = torch.rand(100, 50)
index1 = torch.rand(100)
index2 = torch.rand(100)
num_features = 8
dataset = cebra.data.DatasetCollection(
cebra_sklearn_dataset.SklearnDataset(session1, (index1, )),
cebra_sklearn_dataset.SklearnDataset(session2, (index2, )))
model = nn.ModuleList([
cebra.models.init(
name="offset1-model",
num_neurons=dataset.input_dimension,
num_units=32, …
```

Add `...` pattern to copybutton config

---

cebra/integrations/sklearn/metrics.py
docs/source/api.rst
docs/source/api/sklearn/helpers.rst

Fix #24 
Thanks to @drsax93 for flagging and testing!
I also added the required functions to the docs.
|Before|After|
|-|-|
|![image](https://github.com/AdaptiveMotorControlLab/CEBRA/assets/727984/a507475f-37d3-48ad-8e85-d3cc856d83ac)|![image](https://github.com/AdaptiveMotorControlLab/CEBRA/assets/727984/6b8ea2a1-f7e2-4ec5-acc8-4b795362f700)
|

Expose `n_bins` argument from `align_embeddings`

---

setup.cfg

As of march 24, the `nlb_tools` package [is available on pypi](https://github.com/neurallatents/nlb_tools/issues/9#issuecomment-1483240302). This PR adds the original dependency back in to avoid the manual installation.
For future reference, the original nlb_tools package used/recommended as "git+https://github.com/neurallatents/nlb_tools@065cb137ea3f9ecff4d237d2d404bf7a3c2890de"
Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/issues/665

Add NLB tools pypi package back as dataset dependency

---

cebra/helper.py
cebra/integrations/matplotlib.py
tests/test_plot.py

This pull request introduces a custom decorator `@requires_package_version` enabling the specification of the required package version for a specific function. We use it to specify the version of `compare_models()` function since it requires Matplotlib version 3.6 or higher.
Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/639
Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/issues/580

Add Matplotlib ImportError when using compare_models()

---

cebra/helper.py
tests/test_dlc.py

We observed a test failure in #59 , most likely due to rate limits when downloading raw data for testing from github. This PR replaces [some of the links](https://github.com/AdaptiveMotorControlLab/CEBRA/blob/a21ba0ec17a8c7cc67fc24187f119a52c4132cd0/tests/test_dlc.py#L23-L25) with references to [figshare](https://figshare.com/s/b917317bfab725e0b207) which is probably better suited to host the files.

Fix test failures due to http rate limit

---

cebra/integrations/sklearn/cebra.py
tests/test_sklearn.py

Hi all, thank you very much for this great work.
I have been using the latest stable release of Cebra for my work on a summer research project. I recently switched to a new MacBook, so today I tried using main branch as it has MPS compatibility. I came across an issue with the recently added `to()` method within the CEBRA class for sklearn integration. 
From my understanding:
The recently implemented `to()` method within the CEBRA class in sklearn integration has a bug in the type of the class attributes `device` and `device_`. The two bugs are:
- The logic of the if statements for type checking breaks when device is of type torch.device because of `device.startswith()`, which assumes device is of type str, yet the input type hint is `device: Union[str, torch.device]`
- When the method is …

Fix type bug in to() method

---

Makefile
PKGBUILD
cebra/__init__.py
reinstall.sh

Release 0.3.0rc1

---

cebra/datasets/__init__.py
cebra/datasets/synthetic_data.py

Introduces a new dataset for synthetic data.
Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/641
Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/720

Autodownload synthetic data

---

.gitignore
Makefile
cebra/datasets/hippocampus.py
cebra/models/multiobjective.py
docs/source/contributing.rst
tools/build_docs.sh

This PR makes it easier to locally build and test the documentation.
The components are:
- Update the contribution guide which will get published on https://cebra.ai/docs/contributing.html
- Add a script at `./tools/build_docs.sh` which will check-out all additional repositories, trigger a docs build, and start a webserver to inspect the build at http://127.0.0.1:8080/

Improve documentation for local docs build

---

cebra/integrations/plotly.py

Plotly integration

---

cebra/__init__.py
cebra/models/criterions.py
tests/test_criterions.py

This PR fixes https://github.com/AdaptiveMotorControlLab/CEBRA/issues/48 in the numerically stabilized version of the InfoNCE loss function. It also adds numerical tests for the infoNCE implementation.
Note: Although we verified that this change does not meaningfully influence the algorithm outputs (e.g., in the demo notebooks), it is not advised to do model comparisons across models trained before (up to 0.3.0rc1) and after (from 0.3.0rc2 onwards) this modification.
Thanks to @mudphudwang for flagging.
Fix https://github.com/AdaptiveMotorControlLab/CEBRA/issues/48
Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/658

Fix broadcasting in InfoNCE loss

---

cebra/data/load.py
cebra/datasets/monkey_reaching.py
tests/test_criterions.py
tests/test_load.py

As discussed in #57 , the error messages when using `cebra.load` and other parts of the code can be improved. This PR fixes #77 and adds more context to all error messages for `cebra.load`, and also removes the confusing error message about the `nlb_tools` package in the demo notebooks.
It turns out that this module is only needed when accessing the raw NWB files, but not for loading the preprocessed files we host on figshare. The error is hence moved into that particular loading function.
Fix #77

Enhance `ModuleNotFoundError` messages

---

cebra/integrations/matplotlib.py
cebra/integrations/sklearn/metrics.py
docs/source/usage.rst
tests/test_plot.py
tests/test_sklearn_metrics.py

- I removed the possibility of using both the between-runs and between-datasets at the same time. 
- I removed the possibility to add `dataset_ids` for the between-runs consistency. The labels will be `np.arange(len(embeddings))` always.
- The embeddings provided for between-runs must be the same number of samples (as no alignment is happening), but the number of output dimensions can be different.
- I re-wrote the tests: 2 functions one for each (datasets / runs).
- I re-wrote some of the examples in the usage file so that the tests pass.
to do: 
Maybe need better documentation in the usage file for instance.
---
Fix https://github.com/AdaptiveMotorControlLab/CEBRA/issues/27
Fix #54

Fix consistency labels ordering and simplify

---

.github/workflows/build.yml
PKGBUILD
cebra/integrations/matplotlib.py
cebra/integrations/plotly.py
setup.cfg
tests/test_plotly.py

Adds `plotly` integration for better interactive plots in notebooks/demos.
Implemented by @nastya236 
Usage example (e.g. in a jupyter notebook):
``` python
import cebra
import numpy as np
import cebra.integrations.plotly
data = cebra.datasets.init("rat-hippocampus-single-achilles")
X = np.random.uniform(0, 1, (100, 50))
y = np.random.uniform(0, 10, (100, 5))
cebra_model = cebra.CEBRA(max_iterations=3000, batch_size = 512, verbose = True)
cebra_model.fit(data.neural)
embedding = cebra_model.transform(data.neural)
time = np.arange(len(data))
fig = cebra.integrations.plotly.plot_embedding_interactive(embedding, embedding_labels=data.index[:,0])
fig.show()
```
---
Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/747
Fix …

Add interactive plots using plotly

---

setup.cfg

`tables` made a really fresh release of 3.9.0 on Oct 5, and 3.9.1 on Oct 6, which breaks the current build. We'll restrict to the previous version and then further investigate the root issue.
See: https://pypi.org/project/tables/3.9.1/

Pin `tables` <= 3.8

---

Dockerfile
Makefile
PKGBUILD
cebra/__init__.py
reinstall.sh
tests/test_plotly.py

Release  v0.3.0

---

cebra/__init__.py
cebra/integrations/__init__.py

- note that plotly is an integration we support

Auto-import plotly integration

---

cebra/integrations/plotly.py

Updates an example in the docstrings, users should use the shortcut `cebra.plot_embedding_interactive` which is available since #96 .

Simplify plotly docstring example

---

.github/workflows/docs.yml
cebra/data/load.py
cebra/integrations/plotly.py
docs/source/api.rst
docs/source/api/integrations/data.rst
docs/source/api/integrations/deeplabcut.rst
docs/source/api/integrations/matplotlib.rst
docs/source/api/integrations/plotly.rst
docs/source/api/pytorch/helpers.rst
docs/source/api/pytorch/integrations.rst
docs/source/conf.py

This adds a new category "Integrations" to the API docs. The goal is to increase visibility of a few relevant helper functions, e.g. for data loading and plotting.
The new docs after merging this PR would look like this:

Restructure API docs for integrations

---

Dockerfile
Makefile
PKGBUILD
README.md
cebra/__init__.py
reinstall.sh
tools/bump_version.sh

This is the release PR for v0.3.1, the biggest change is the integration of various PRs for easier use of the plotly integration (#103 , #102 , #96 ).
I also added a tool for easier bumping the package version, as it is distributed to quite a few places in the codebase. This tool can be run as follows:
```
./tools/bump_version.sh 0.3.1rc1
```
Open TODOs:

Release v0.3.1rc1

---

.github/workflows/build.yml
conda/cebra.yml
conda/cebra_paper_m1.yml

- updated the name of env to match file name
- removed constraint on python version and removed nb_conda; tested on m2 mac

Update cebra_paper_m1.yml and cebra.yml

---

cebra/integrations/sklearn/cebra.py
tests/test_sklearn.py

temporary fix #108 
For now multisession training `adapt=True` is not implemented. This PR handles a case that was not caught (multisession training, single session adapt) and add the corresponding test.

Add missing error raising and test for `adapt` on Multissession

---

LICENSE.md
NOTICE.yml
README.md
docs/source/index.rst

This PR changes the license to Apache 2.0, and will be part of the 0.4.0 release (https://github.com/AdaptiveMotorControlLab/CEBRA/pull/116).
It adapts the LICENSE doc, the NOTICE, and some text in the README and the website that references the license.
Close https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/772

Change license to Apache 2.0

---

cebra/integrations/plotly.py
tests/test_plotly.py

Fixed `showlegend` `**kwargs` in plotly scatter 3D. 
```
from cebra.integrations.plotly import plot_embedding_interactive
import numpy as np
embedding = np.random.randn(100, 3)
labels = np.random.randint(0, 10, 100)
plot_embedding_interactive(embedding, labels, markersize=10, showlegend=True)
```
```
plot_embedding_interactive(embedding, labels, markersize=10)
```

Fixed showlegend for plotly

---

cebra/integrations/plotly.py
tests/test_plotly.py

Pass showlegend/template kwargs to plotly

---

docs/source/conf.py
setup.cfg

In #135 , the tests show a few errors that are due to upstream changes in our dependencies. This PR fixes the build errors:
- Update the URL of the pandas intersphinx mapping to the current stable version (vs. the dev version, which we used previously). This fixes the issue during docs build due to a missing reference.
- Pin `pytest` and `pytest-sphinx` to a previous release --- we use `pytest-sphinx`, which is not yet compatible with the latest `pytest` version.

Fix pandas intersphinx mapping; fix test setup

---

third_party/pivae/pivae_code/pi_vae.py

this is required to run piVAE on colab with latest TF/keras; see updated notebook as well that needs merged : https://github.com/AdaptiveMotorControlLab/CEBRA-demos/tree/mwm/fix-synthetic

Update imports in pivae from `keras` to `tensorflow.keras`

---

.github/workflows/build.yml
Dockerfile
Makefile
cebra/integrations/plotly.py
docs/source/usage.rst
setup.cfg
tests/test_criterions.py
tests/test_dlc.py
tools/build_docker.sh
tools/build_docs.sh

Fixes several issues with the test suite:
- Fix an issue in `test_criterions`: Most likely due to some change to the torch version (?), running the `test_infonce_gradients` test twice causes non-deterministic behavior. On the first run, non-existent gradients are `None` as expected, but on the second run, they are set to a zero torch array. I added a hotfix and accept both `None` and a zero array as possible values now, but this needs to deeper digging to fix properly.
- The `usage.rst` docs had a typo following the intro of discrete multisession training ( #135 ), which was fixed by introducing a separate variable name for the discrete multisession model there.
- Docs building failed. Removed pinning of `scikit-learn` and added a pin to `numpy<2` instead. In a future PR, we should look …

Upgrade dependencies and fix testsuite

---

cebra/datasets/monkey_reaching.py
cebra/integrations/plotly.py
setup.cfg

Update: The root issue was numpy 2. This is a recent upgrade (June 2024), and it seems like many of the packages required for cebra do not easily work with npy2 (yet). Errors included `pandas/pytables`, but also `torch`. It would be probably possible to work around these errors, but I think it is not worth yet --- in half a year or so, the situation is probably more stable, and we can remove the pinning.
This PR now does the following changes:
- Pin `numpy` below v2. 
- Remove `nlb_tools` to allow use of more recent pandas versions. This will only affect users who want to use the monkey dataset. We provide guidance on how to post-hoc install the package directly via a warning for these users.
- Fix a minor issue in the plotly code, which arises because we now use more recent versions of …

Fix tests for upgraded dependencies

---

.pre-commit-config.yaml
pyproject.toml

Adds [`ruff`](https://docs.astral.sh/ruff/) for linting the whole codebase. Config is done in the `project.toml`, and added to the `pre-commit` hooks.
Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/662
The actual fixes will be added to a dedicated PR to avoid clutter: https://github.com/AdaptiveMotorControlLab/CEBRA/pull/185

Add ruff for linting the codebase

---

cebra/data/datasets.py
cebra/helper.py

This allows for someone to use discrete labels in a continuous way; this might change the solver to behaviors you might not be expecting so please use with caution.
fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/791
fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/issues/790

Extend type checking to all float datatypes

---

cebra/data/datasets.py

Set default offset to an Offset object

---

cebra/data/datasets.py
tests/test_datasets.py

PRs #166 and #180 did some changes to the TensorDataset class without adding tests. This PR adds such tests to cover the basic functionality (type checking, init of the dataset, accessing the data and reproducing the issue described in #174 ).
This brought two minor errors to light which are also fixed in the PR (typo in `self._to_tensor(discrete, check_dtype="integer")`, wrong docstring, exception handling.

Add additional tests for TensorDataset

---

tests/test_api.py
tests/test_cli.py
tests/test_criterions.py
tests/test_datasets.py
tests/test_demo.py
tests/test_distributions.py
tests/test_grid_search.py
tests/test_integration_train.py
tests/test_load.py
tests/test_models.py
tests/test_plot.py
tests/test_registry.py
tests/test_sklearn.py
tests/test_solver.py
tests/test_usecases.py

After #185 in `cebra/`, this PR fixes the remaining errors in the `tests/` directory. Mostly unused variables or double names, no errors spotted.

Fix linting errors in tests

---

conda/cebra_paper.yml
conda/cebra_paper_m1.yml

Update the `sklearn` ref in the conda files to `scikit-learn` as discussed [here](https://github.com/scikit-learn/sklearn-pypi-package).
Fix #194

Fix `scikit-learn` reference in conda environment files

---

.github/workflows/build.yml
cebra/integrations/sklearn/cebra.py

Fix #204 
sklearn 1.6.0 was released on Dec 9, 24 and introduced a new mechanism for specifying estimator tags (https://scikit-learn.org/dev/developers/develop.html). This PR adopts CEBRA to comply with this new notation. Older sklearn variants will fall back to the `more_tags()` functions as recommended [in this comment](https://github.com/scikit-learn/scikit-learn/pull/29677#issuecomment-2334229165).
Indepedently, I spotted a bug in the inheritance order in the CEBRA class, which was fixed now, as described [here](https://scikit-learn.org/stable/developers/develop.html#rolling-your-own-estimator).
Finally, since the code is now version dependent and there might be users rolling older sklearn version, I extended the test suite by one case checking with a legacy sklearn version (version …

Add support for new __sklearn_tags__

---

cebra/solver/base.py
tests/test_sklearn.py

fix #199.
To still transform the extra samples that are not contained in a full batch while not getting an error regarding the next to last batch `batch_end_idx` above the length of the input, I propose to concatenate the penultimate batch (so the last complete batch) with the last batch (the incomplete batch from 1 to `batch_size`).

Concatenate last batches for batched inference

---

.github/workflows/build.yml
.github/workflows/doc-coverage.yml
.github/workflows/docs.yml
.github/workflows/release-pypi.yml

Several current PRs, eg #206 #189  fail due to an outdated python action.
This PR upgrades all actions to v5, the latest version (https://github.com/actions/setup-python/blob/1928ae624dc06094d8c65f021a4700ea8fa56b9d/README.md).
In the same spirit we update actions/cache from outdated version to v4 to avoid the deprecation scheduled to happen soon.

Update workflows to actions/setup-python@v5, actions/cache@v4

---

cebra/integrations/sklearn/metrics.py
tests/test_sklearn_metrics.py

This adds a better goodness of fit measure. Instead of the old variant which simply matched the InfoNCE and depends on the batch size, the proposed measure
- is at 0 for "chance level" (vs. log batch size)
- does not need an adjustment for single session vs. multi-session solvers
- increases as the model gets better, which might be more intuitive
The conversion is quite simply done via
```
GoF(model) = log (batch_size_per_session * num_sessions) - InfoNCE(model)
```
This measure is also used in [DeWolf et al., 2024, Eq. (43)](https://www.biorxiv.org/content/10.1101/2024.09.11.612513v1)
Application example (GoF improves from 0 to a larger value during training):
---
OLD example, for comparison
---
Close https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/669

Add improved goodness of fit implementation

---

.github/workflows/build.yml
cebra/data/load.py
cebra/integrations/sklearn/cebra.py
setup.cfg
tests/test_dlc.py
tests/test_load.py

Numpy was pinned to `1.x` before. Checking if an upgrade to `2.x` is possible.
Background: The dependency was pinned in https://github.com/AdaptiveMotorControlLab/CEBRA/pull/172 due to issues with sklearn and docs building. Given the updates we made to fix new sklearn versions (#205 etc.), let's explore if we can drop the constraint by now.
New insights: PyTables is the remaining root cause preventing us from upgrading fully. This is only the issue for the `pd.read_hdf` function. The proposed fix is to attempt loading with `pandas` via `pytables`, but if this fails we can manually load using `h5py`, and then construct the `pandas` dataframe from there.
There are new libraries like `polars` coming up, but it seems like these do not have hdf support yet …

Support numpy 2, upgrade tests to support torch 2.6

---

cebra/integrations/matplotlib.py

The maximum consistency value was set to 99 when plotting the consistency matrix. This is a fix so that max is set to 100 instead.

Change max consistency value to 100 instead of 99

---

cebra/data/assets.py

- mkdir was failing in data download in 0.5.0rc1; attempt to fix; I think this is effectively a small revert of a change introduced in #169 
locally works: 
```
In [1]: import cebra
In [2]: import cebra.datasets
...: from cebra import CEBRA
In [3]: hippocampus_pos = cebra.datasets.init('rat-hippocampus-single-achilles')
100%|████████████████████████████████████████████████████████████████| 10.0M/10.0M [00:00<00:00, 31.3MB/s]
Download complete. Dataset saved in 'data/rat_hippocampus/achilles.jl'
```

Update assets.py --> force check for parent dir

---

docs/source/figures.rst
docs/source/index.rst
docs/source/installation.rst
docs/source/usage.rst

- small changes to home/landing page
- changed ref. of figures to 2023
- added ref to 2025 paper

General Doc refresher

---

.github/workflows/docs.yml
cebra/integrations/plotly.py
docs/Makefile
docs/source/_static/css/custom.js
docs/source/conf.py

The issue was that plotly was not rendering in our sphinx docs
Solution is from: https://github.com/spatialaudio/nbsphinx/issues/128#issuecomment-1158712159
Also took inspiration from https://github.com/VectorInstitute/cyclops/pull/591 
Added version builds

render plotly in our docs, show code/doc version

---

AUTHORS.md
setup.cfg

The goal is to consolidate the setup options. Note, this may cause backwards changes in people's installation setup, but is a minor change.
added an authors page with new links to CEBRA extensions

Refactoring setup.cfg

---

.github/workflows/docs.yml
docs/root/robots.txt

This is an oversight from an early release; now that docs are stable, we should let search engines index the docs.

Allow indexing of the cebra docs

---

cebra/integrations/sklearn/helpers.py
tests/test_sklearn_metrics.py

When running `align_embeddings(embeddings, labels, normalize=False)` `quantized_embedding_norm` in `quantized_embeddings.append(quantized_embedding_norm)` is undefined. 
Solved by appending `quantized_embedding` to `quantized_embeddings` instead when `normalize=False`.

Fix quantized_embedding_norm undefined when `normalize=False`

---

cebra/integrations/matplotlib.py
cebra/integrations/plotly.py
setup.cfg
tests/test_plotly.py

- Replace matplotlib.cm.get_cmap() with matplotlib.colormaps.get_cmap()
- Replace plt.get_cmap() with matplotlib.colormaps.get_cmap()
- Update cebra/integrations/plotly.py, matplotlib.py, and tests/test_plotly.py
- Remove matplotlib<3.11 version pin from setup.cfg
- Ensures future compatibility with matplotlib 3.11+ releases
Fixes #240

Fix matplotlib colormap deprecation warnings for 3.11 compatibility
